### ISSUE TITLE
Feat: Add trading symbol compatibility

### ISSUE THREAD

**Issue by ba11b0y** [5paisa/py5paisa#1]
Feature request:

### Existing
 - The API needs a scrip code to place an order.

### Requested feature

 - Give the users an option to place orders using either of scrip code or a trading symbol

**Comment by invinciblycool** [comment]
Scrip codes doesn't seem to work with NSE as the exchange type.

**Comment by uberdeveloper** [comment]
Could I try this?

**Comment by invinciblycool** [comment]
Sure @uberdeveloper

**Comment by uberdeveloper** [comment]
Any pointers?
I think we need to convert the existing master and map them to the keyword arguments for the `place_order` function or should we go for a new `order_place` function similar to Zerodha?

**Comment by invinciblycool** [comment]
Hey @uberdeveloper 
So I have been working on a GET endpoint which will return the scrip code for matching trading symbol.
I have written it for NSE cash and will soon be completing it for NSE Futures and Options also.
Does this help?

**Comment by uberdeveloper** [comment]
@invinciblycool 
Thanks definitely.
So would this be a part of the existing `place_order` function or a new `order_by_symbol` function?
I prefer a function in the form
`client.order_place(symbol='SBIN', exchange='NSE',qty=1,**kwargs)`
where the exchange and symbol would be converted to the scrip_code and order would be placed.

The entire instruments file could be preloaded on a request so that the (symbol, exchange) tuple could be looked up for scrip code and vice-versa (scrip codes can be duplicates since they are used across exchanges)

Could I give a try in implementing this?

**Comment by rrjain1** [comment]
@invinciblycool any update on this feature for NSE Futures and Options... would be a great help if this can be released on priority.
